create table if not exists public.bot_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  bot_mode text not null default 'buyer',
  name text not null default '',
  company text not null default '',
  phone text not null default '',
  email text not null default '',
  city text not null default '',
  budget text not null default '',
  service text not null default '',
  objective text not null default '',
  source text not null default 'super-ai-bot',
  extras jsonb not null default '{}'::jsonb
);

create index if not exists bot_leads_created_at_idx on public.bot_leads (created_at desc);
create index if not exists bot_leads_phone_idx on public.bot_leads (phone);
